name: example
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+2

environment:
  sdk: ">=2.12.0-29.10.beta <2.12.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view:
    path: ../

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
