name: flutter_staggered_grid_view
description: A Flutter staggered grid view (masonry tiles) which supports multiple columns with rows of varying sizes
version: 0.4.1
homepage: https://github.com/letsar/flutter_staggered_grid_view

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.5.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.24.0-6.0.pre"
